// <auto-generated />
using System;
using MediaoManage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaoManage.Migrations
{
    [DbContext(typeof(MediaoManageContext))]
    partial class MediaoManageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediaoManage.Models.UserMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("container_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("media_created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("media_deleted")
                        .HasColumnType("datetime2");

                    b.Property<string>("media_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("media_file_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("media_file_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("media_modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("media_status")
                        .HasColumnType("int");

                    b.Property<string>("media_tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("media_thumbnail_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("media_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("media_uploaded")
                        .HasColumnType("datetime2");

                    b.Property<string>("media_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserMedia");
                });
#pragma warning restore 612, 618
        }
    }
}
